kind: Deployment
image:
  tag: 2.1.8-debug
replicaCount: 1

rbac:
  eventsAccess: true

extraVolumes:
- name: events-file
  emptyDir: {}

extraVolumeMounts:
- mountPath: /tmp/v4m
  name: events-file
  subPath: k8s_events.json

env:
   - name: ES_LOGCOLLECTOR_USER
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: username
   - name: ES_LOGCOLLECTOR_PASSWD
     valueFrom:
       secretKeyRef:
         name: internal-user-logcollector
         key: password


config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Parsers_File viya-parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        storage.path /tmp/fb_buffer/
        storage.checksum off
        storage.sync normal
        storage.backlog.mem_limit 5M
        storage.metrics On

  inputs: |
    [INPUT]
        name kubernetes_events
        tag k8s_events
    [INPUT]
        name tail
        tag kube.*
        path /tmp/v4m/*.json
        parser json

  outputs: |
    #[OUTPUT]
    #    name stdout
    #    match k8s_events
    #    format json_lines
    [OUTPUT]
        name file
        match k8s_events
        format plain
        file /tmp/v4m/k8s_events.json
    [OUTPUT]
        Name  opensearch
        Alias opensearch_events
        Match kube.*
        Host  v4m-search
        Port  9200
        Buffer_Size 512KB
        Logstash_Format On
        Retry_Limit 5
        Suppress_Type_Name On
        Workers 2
        Time_Key @timestamp
        #Include_Tag_Key: added for debugging
        #Include_Tag_Key    On
        Generate_ID  On
        ##ID_Key $properties['eventid']
        Replace_Dots On
        Logstash_Prefix viya_events
        HTTP_User ${ES_LOGCOLLECTOR_USER}
        HTTP_Passwd ${ES_LOGCOLLECTOR_PASSWD}
        tls         on
        tls.debug   2
        tls.verify  off

  filters: |
    [FILTER]
        Name modify
        Match *
        Set  fb_configMap_version event19
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Buffer_Size         128KB
        Cache_Use_Docker_Id On
        Merge_Log           On
        Merge_Log_Key       json_log
    [FILTER]
        Name modify
        Match kube.*
        set logsource KUBE_EVENT2
        rename $involvedObject['namespace'] k8s_namespace
        rename $source['host']              k8s_host
        copy lastTimestamp         timeStamp
        copy type                  level
        #rename message message
        rename firstTimestamp      PROPS__firsttimestamp
        rename lastTimestamp       PROPS__lastimestamp
        rename count               PROPS__count
        rename type                PROPS__type
        rename reason              PROPS__reason
        rename clusterName         PROPS__clustername
        ##rename $involvedObject['kind'] PROPS__object_type
        ##rename $involvedObject['name'] PROPS__object
        rename $metadata['uid']    PROPS__eventid
        ##rename $metadata['name']       PROPS__metaname
        rename metadata JUNK__metadata
        #rename metadata mdata
        rename involvedObject JUNK__involvedObject
    #[FILTER]
        #Name modify
        #Match kube.*
        #rename $mdata['name']       PROPS__metaname
        #rename $mdata['uid']       PROPS__eventid
        #rename mdata JUNK__metadata
    [FILTER]
        #
        # Create 'properties' map
        # ..any PROPS_ objects are included
        #
        Alias           nest_PROPS_under_properties
        Name            nest
        Match           *
        Operation       nest
        Wildcard        PROPS__*
        Nest_under      properties
        Remove_prefix   PROPS__
    [FILTER]
        Alias           nest_junk
        Name            nest
        Match           *
        Operation       nest
        Wildcard        JUNK__*
        Nest_under      zzzjunk
        Remove_prefix   JUNK__

